#!/bin/sh
cd "${0%/*}" || exit 1
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions

#------------------------------------------------------------------------------

restore0Dir

runApplication blockMesh

runApplication topoSet

runApplication createPatch -overwrite

runApplication -s sludge topoSet

runApplication decomposePar

runParallel $(getApplication)

runApplication reconstructPar

#------------------------------------------------------------------------------
